const fs = require('fs')  
const p = require('path')  
const b = p.join(process.cwd())  
fs.mkdirSync(p.join(b, 'server'), { recursive: true })  
fs.mkdirSync(p.join(b, 'client'), { recursive: true })  
fs.mkdirSync(p.join(b, 'client/src'), { recursive: true })  
fs.mkdirSync(p.join(b, 'client/src/components'), { recursive: true })  
fs.mkdirSync(p.join(b, 'client/public'), { recursive: true })  
fs.mkdirSync(p.join(b, 'docs'), { recursive: true })  
console.log('Directories created')  
